### ISSUE TITLE
missing routes/quazar.php

### ISSUE THREAD

**Issue by therobb** [YABhq/Quazar#20]
i get this error when traying to run php artisan vendor:publish

`App\Providers\RouteServiceProvider::App\Providers\{closure}(): Failed opening required '/home/u432927737/public_html/taspagrafer _site/routes/quazar.php' (include_path='.:/opt/alt/php71/usr/share/pear')
`
i can't find routes/quazar.php in my routes folder.

**Comment by mlantz** [comment]
This package is undergoing some large changes and is being rebranded, the release is coming soon
