### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by hqin2013** [YABhq/Quazar#21]
I setup the Commerce as the document(https://docs.grafite.ca/commerce/) say,found these problems:

1. there is no file app/Modules/UserModel.php

>  use Grafite\Commerce\Services\Concerns\hasFavorites; 

2 . php artisan vendor:publish ,get error:
`Uncaught ErrorException: require(xxxx\routes/commerce.php): failed to open stream: No such file or directory in xxxx\app\Providers\RouteServiceProvider.php:59`
and i don't find commerce.php in route directory

Regards
hqin

**Comment by hqin2013** [comment]
After N times try, i setup half - success:

1. use app/Models/User.php instead of app/Modules/UserModel.php
2. rename cms.php to commerce.php in Routes directory  .

But get errors with Commerce

**Comment by Vandereij** [comment]
I have the same exact issue. 

Is there a way to fix this, please?

**Comment by mlantz** [comment]
I'm at the Laravel conference for the next couple days but this is on my list to review documentation and any bugs that may be present. I apologize for any inconvenience.

**Comment by Vandereij** [comment]
Hi Matt,

did you manage to look into it, by any chance?

Thanks,
Stefano

**Comment by mlantz** [comment]
This has been added to my review list for this week. Will report back shortly.

**Comment by vystepanenko** [comment]
Same here. there is no app/Modules/UserModel.php and routes/commerce.php

**Comment by mlantz** [comment]
Most of the issues in relation to this are typos and order of operations. the User statement should be `app/Models/User.php` clearly I was tired when writing that. 

As for the `routes/commerce.php` that file will not appear until the command `artisan vendor:publish` has been run, since the file has not been published into your applications yet. I've updated the docs to follow the proper order of operations. Sorry for the delay in this.

**Comment by hqin2013** [comment]
hey mlantz, thank you, it works now !

One small problem:
When i add "@extends('quazar-frontend::layouts.store')" to login.blade.php

it tips error:

> No hint path defined for [quazar-frontend]

any suggestion?

**Comment by mlantz** [comment]
Should be `@extends('commerce-frontend::layouts.store')` I've been heavily reviewing all docs and keep finding small issues I'll be updating them all shortly
